version: "3.5"

services:
  moquitto:
    image: "eclipse-mosquitto:2.0.11"
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./config:/mosquitto/config
    restart: unless-stopped

volumes:
  config:
