version: "3.5"

services:
  moquitto:
    image: "eclipse-mosquitto:2.0.11"
    container_name: "mosquitto"
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - ./config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
    restart: unless-stopped
    networks:
      - watcher

  go-watcher:
    image: "tarcisiodf23/go-watcher:0.0.2"
    container_name: "go-watcher"
    restart: unless-stopped
    networks:
      - watcher
    volumes:
      - "./file-watched:/tmp/files"

  watcher-view:
    image: "tarcisiodf23/watcher-view:0.0.1"
    container_name: "watch-view"
    restart: unless-stopped
    networks:
      - watcher
    ports:
      - "8000:80"

networks:
  watcher:

volumes:
  store:
  config:
  mosquitto-data:
  mosquitto-logs:
  mosquitto-conf:
